[package]
name = "svt-agent"
version = "0.1.2"
authors = ["Vladyslav Korniienko <vk.tiamo@gmail.com>"]
repository = "https://github.com/mfactory-lab/svt-agent"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0.66"
clap = { version = "^4.0.29", features = ["derive"] }
anchor-client = "^0.25.0"
anchor-lang = "^0.25.0"
hyper = { version = "0.14", features = ["client"] }
tokio = "^1.22.0"
tracing = "^0.1.37"
tracing-subscriber = { version = "^0.3.16", features = ["env-filter"] }
tracing-tree = "^0.2.2"
futures = "0.3.25"
regex = "^1.7.0"
sha2 = "^0.10.6"
chacha20poly1305 = "0.9"
curve25519-dalek = { version = "^3.2", default-features = false }
x25519-dalek = "^1.2.0"
zeroize = "^1.3.0"
shiplift = "0.7"
serde_json = "^1.0.89"
sled = "0.34.1"
rand = "0.7.3"

[dev-dependencies]
tracing-test = "0.2.3"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = "fat"
#panic = "abort"
debug = false
