[package]
name = "svt-agent"
description = ""
version = "0.1.37"
authors = ["Vladyslav Korniienko <vk.tiamo@gmail.com>"]
repository = "https://github.com/mfactory-lab/svt-agent"
edition = "2021"

[dependencies]
anyhow = "^1.0"
clap = { version = "^4.0", features = ["derive", "env"] }
chrono = { version = "^0.4", features = ["clock"] }
anchor-client = "^0.26.0"
anchor-lang = "^0.26.0"
hyper = { version = "0.14", features = ["client"] }
tokio = "^1.22"
tracing = "^0.1"
tracing-subscriber = { version = "^0.3", features = ["env-filter"] }
tracing-tree = "^0.2"
futures = "0.3"
regex = "^1.7"
sha2 = "^0.10"
chacha20poly1305 = "0.9"
curve25519-dalek = { version = "^3.2", default-features = false }
x25519-dalek = "^1.2.0"
zeroize = "^1.3.0"
shiplift = "0.7"
serde_json = "^1.0.89"
sled = "0.34.1"
rand = "0.7.3"
influxdb = { version = "0.5.2", features = ["derive"] }

[dev-dependencies]
tracing-test = "0.2.3"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = "fat"
#panic = "abort"
debug = false
