[package]
name = "svt-agent"
version = "0.1.0"
authors = ["Vladyslav Korniienko <vk.tiamo@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.23", features = ["derive"] }
anchor-client = "0.25.0"
anchor-lang = "0.25.0"
tokio = "1.21.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-tree = "0.2.2"
futures = "0.3.25"
regex = "1.7.0"
sha2 = "0.10.6"
chacha20poly1305 = "^0.9"
curve25519-dalek = { version = "3.2", default-features = false }
x25519-dalek = "1.2.0"
#reqwest = { version = "0.11.12", features = ["json"] }
#solana-client = "1.10.32"
#solana-program = "1.10.32"
#thiserror = "1.0.37"
