- name: Update Agent
  hosts: all

  vars:
    container_name: svt-agent
    image_name: ghcr.io/mfactory-lab/svt-agent:latest

  tasks:
    - name: Pull new image
      docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Restart container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        restart: yes
        state: started
        stop_timeout: 1
        force_kill: yes

#    - name: Start a container
#      docker_container:
#        name: "{{ container_name }}"
#        image: "{{ image_name }}"
#        state: started
#        restart: yes
#        detach: yes
#        ports:
#          - "8080:8080"
#        env:
#          SECRET_KEY: "ssssh"
#          # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
#          BOOLEAN_KEY: "yes
