- name: Update Agent
  hosts: localhost
  connection: local
  vars:
    base_image: mfactory-lab/svt-agent
    container_name: svt-agent
  tasks:
    - name: Download new image
      docker_image:
        name: {{ base_image }}
        source: pull
    - name: Restart container
      docker_container:
        name: {{ container_name }}
        image: {{ base_image }}
        state: started
        restart: yes
#      local_action: command docker container restart {{ container_name }}
#    - name: Start a container
#      docker_container:
#        name: {{ container_name }}
#        image: {{ base_image }}
#        state: started
#        restart: yes
#        detach: yes
#        ports:
#          - "8080:8080"
#        env:
#          SECRET_KEY: "ssssh"
#          # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
#          BOOLEAN_KEY: "yes
