- name: Update Agent
  hosts: all

  vars:
    base_image: ghcr.io/mfactory-lab/svt-agent:{{ version | default(latest) }}
    container_name: svt-agent

  tasks:
    - name: Pull new image
      docker_image:
        name: "{{ base_image }}"
        source: pull

    - name: Restart container
      docker_container:
        image: "{{ base_image }}"
        name: "{{ container_name }}"
        restart: yes
        state: started
        stop_timeout: 1
        force_kill: yes

#    - name: Start a container
#      docker_container:
#        name: {{ container_name }}
#        image: {{ base_image }}
#        state: started
#        restart: yes
#        detach: yes
#        ports:
#          - "8080:8080"
#        env:
#          SECRET_KEY: "ssssh"
#          # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
#          BOOLEAN_KEY: "yes
