name: Publish Page Dev

on:
  push:
    branches: [ dev ]
    paths:
      - install.sh
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy Files
        run: mkdir dist && cp install.sh ./dist/dev-install.sh

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
